import type { MTOResponse } from "./types";

/**
 * Exports the MTO as an XLSX file using SheetJS (xlsx package).
 * Falls back gracefully if the package isn't available.
 *
 * The workbook contains two sheets:
 *   - "MTO Items"    : the flat line-item table
 *   - "Summary"      : the computed summary block + drawing metadata
 */
export async function exportExcel(mto: MTOResponse): Promise<void> {
  let XLSX: typeof import("xlsx");
  try {
    XLSX = await import("xlsx");
  } catch {
    throw new Error(
      "Excel export requires the 'xlsx' package. Run: npm install xlsx"
    );
  }

  const wb = XLSX.utils.book_new();

  // ── Sheet 1: MTO Items ──────────────────────────────────────────────────────
  const itemRows = mto.items.map((item) => ({
    "Item #": item.item_no,
    Category: item.category,
    Description: item.description,
    "Size (NPS)": item.size_nps ?? "",
    "Sched / Rating": item.schedule_rating ?? "",
    "Material Spec": item.material_spec ?? "",
    "End Type": item.end_type ?? "",
    Quantity: item.category === "PIPE" ? (item.length_m ?? item.quantity) : item.quantity,
    Unit: item.category === "PIPE" ? "M" : item.unit,
    "Confidence (%)":
      item.confidence != null ? Math.round(item.confidence * 100) : "",
    Remarks: item.remarks ?? "",
  }));

  const wsItems = XLSX.utils.json_to_sheet(itemRows);
  // Set column widths
  wsItems["!cols"] = [
    { wch: 7 }, { wch: 10 }, { wch: 40 }, { wch: 10 }, { wch: 12 },
    { wch: 20 }, { wch: 10 }, { wch: 10 }, { wch: 6 }, { wch: 14 }, { wch: 35 },
  ];
  XLSX.utils.book_append_sheet(wb, wsItems, "MTO Items");

  // ── Sheet 2: Summary ────────────────────────────────────────────────────────
  const { drawing_meta: dm, summary: s } = mto;
  const summaryRows = [
    ["Drawing No.", dm.drawing_no ?? ""],
    ["Revision", dm.revision ?? ""],
    ["Line Number", dm.line_number ?? ""],
    ["NPS", dm.nps ?? ""],
    ["Material Class", dm.material_class ?? ""],
    ["Service", dm.service ?? ""],
    [],
    ["Total Pipe Length (m)", s.total_pipe_length_m],
    ["Fittings", s.fittings],
    ["Flanges", s.flanges],
    ["Valves", s.valves],
    ["Gaskets", s.gaskets],
    ["Bolt Sets", s.bolt_sets],
    ["Field Welds", s.field_welds],
    [],
    ["Generated by", "Isometric → MTO Generator"],
    ["Mock data", mto.mock ? "Yes" : "No"],
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  wsSummary["!cols"] = [{ wch: 22 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

  const filename = `${dm.drawing_no || "mto"}.xlsx`;
  XLSX.writeFile(wb, filename);
}
